name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd ai-genomics-book
          npm install

      - name: Build
        run: |
          cd ai-genomics-book
          npm run build -- --configuration production --base-href=/ai-genomics-book/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ai-genomics-book/dist/ai-genomics-book
          branch: gh-pages
          token: ${{ secrets.GH_TOKEN }}
